export interface StaticDevice {
  k_number: string;
  device_name: string;
  manufacturer: string;
  clearance_date: string;
  product_code: string;
  predicate_k_numbers: string[];
  device_class?: string;
  decision_code?: string;
  decision_description?: string;
}

const staticDevices: StaticDevice[] = [
  {
    k_number: "K100001",
    device_name: "Alpha Glucose Monitor",
    manufacturer: "MediTech Inc.",
    clearance_date: "2010-03-15",
    product_code: "NBW",
    predicate_k_numbers: ["K110001", "K100002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K100002",
    device_name: "Beta Glucose Monitor",
    manufacturer: "MediTech Inc.",
    clearance_date: "2011-04-20",
    product_code: "NBW",
    predicate_k_numbers: ["K110002", "K120001"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K110001",
    device_name: "Delta Heart Monitor",
    manufacturer: "CardioCare LLC",
    clearance_date: "2011-08-10",
    product_code: "DXH",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K110002",
    device_name: "Echo Heart Monitor",
    manufacturer: "CardioCare LLC",
    clearance_date: "2012-02-14",
    product_code: "DXH",
    predicate_k_numbers: ["K100001", "K110001"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K120001",
    device_name: "Nova Insulin Pump",
    manufacturer: "DiabetoTech",
    clearance_date: "2012-06-18",
    product_code: "LZG",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K120002",
    device_name: "Nova Insulin Pump Pro",
    manufacturer: "DiabetoTech",
    clearance_date: "2013-01-22",
    product_code: "LZG",
    predicate_k_numbers: ["K120001", "K110002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K130001",
    device_name: "Pulse Oximeter Lite",
    manufacturer: "OxyHealth",
    clearance_date: "2013-05-30",
    product_code: "DQA",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K130002",
    device_name: "Pulse Oximeter Advanced",
    manufacturer: "OxyHealth",
    clearance_date: "2014-01-12",
    product_code: "DQA",
    predicate_k_numbers: ["K130001", "K120002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K140001",
    device_name: "Smart Thermometer",
    manufacturer: "ThermoTech",
    clearance_date: "2014-07-19",
    product_code: "FLL",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K140002",
    device_name: "Smart Thermometer X",
    manufacturer: "ThermoTech",
    clearance_date: "2015-02-25",
    product_code: "FLL",
    predicate_k_numbers: ["K130002", "K140001"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K150001",
    device_name: "Neo Blood Pressure Monitor",
    manufacturer: "Pressurix",
    clearance_date: "2015-08-10",
    product_code: "DXN",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K150002",
    device_name: "Neo BP Monitor Pro",
    manufacturer: "Pressurix",
    clearance_date: "2016-01-15",
    product_code: "DXN",
    predicate_k_numbers: ["K140002", "K150001"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K160001",
    device_name: "Airflow Spirometer",
    manufacturer: "LungMetrics",
    clearance_date: "2016-06-01",
    product_code: "BZK",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K160002",
    device_name: "Airflow Spirometer Pro",
    manufacturer: "LungMetrics",
    clearance_date: "2017-03-11",
    product_code: "BZK",
    predicate_k_numbers: ["K150002", "K160001"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K170001",
    device_name: "Flex ECG Patch",
    manufacturer: "PatchWave",
    clearance_date: "2017-07-22",
    product_code: "DPS",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K170002",
    device_name: "Flex ECG Patch 2.0",
    manufacturer: "PatchWave",
    clearance_date: "2018-01-10",
    product_code: "DPS",
    predicate_k_numbers: ["K170001", "K160002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K180001",
    device_name: "iBreath Inhaler Tracker",
    manufacturer: "Respira",
    clearance_date: "2018-06-18",
    product_code: "BZQ",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K180002",
    device_name: "iBreath Smart Inhaler",
    manufacturer: "Respira",
    clearance_date: "2019-03-25",
    product_code: "BZQ",
    predicate_k_numbers: ["K180001", "K170002", "K140002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K190001",
    device_name: "EchoWear Hearing Aid",
    manufacturer: "SoundCore",
    clearance_date: "2019-09-03",
    product_code: "EWR",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K190002",
    device_name: "EchoWear Pro",
    manufacturer: "SoundCore",
    clearance_date: "2020-02-14",
    product_code: "EWR",
    predicate_k_numbers: ["K190001", "K180002", "K150002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K200001",
    device_name: "Sleep Monitor Ring",
    manufacturer: "SomnoTrack",
    clearance_date: "2020-07-09",
    product_code: "FLL",
    predicate_k_numbers: [],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K200002",
    device_name: "Sleep Monitor Ring 2.0",
    manufacturer: "SomnoTrack",
    clearance_date: "2021-01-05",
    product_code: "FLL",
    predicate_k_numbers: ["K200001", "K190002", "K160002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K210001",
    device_name: "PulseFit Smart Band",
    manufacturer: "PulseGear",
    clearance_date: "2021-04-12",
    product_code: "DQA",
    predicate_k_numbers: ["K130002", "K200002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K210002",
    device_name: "PulseFit Pro Band",
    manufacturer: "PulseGear",
    clearance_date: "2021-10-30",
    product_code: "DQA",
    predicate_k_numbers: ["K210001", "K150002", "K180002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K220001",
    device_name: "ThermoPatch Temp Sensor",
    manufacturer: "ThermoTech",
    clearance_date: "2022-02-14",
    product_code: "FLL",
    predicate_k_numbers: ["K140002", "K200002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K220002",
    device_name: "ThermoPatch Pro",
    manufacturer: "ThermoTech",
    clearance_date: "2022-08-19",
    product_code: "FLL",
    predicate_k_numbers: ["K220001", "K210002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K230001",
    device_name: "NeoBP Cloud",
    manufacturer: "Pressurix",
    clearance_date: "2023-01-17",
    product_code: "DXN",
    predicate_k_numbers: ["K150002", "K200002", "K180002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K230002",
    device_name: "NeoBP Cloud 2.0",
    manufacturer: "Pressurix",
    clearance_date: "2023-06-23",
    product_code: "DXN",
    predicate_k_numbers: ["K230001", "K210002", "K220002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K240001",
    device_name: "Alpha Glucose AI",
    manufacturer: "MediTech Inc.",
    clearance_date: "2024-01-02",
    product_code: "NBW",
    predicate_k_numbers: ["K100002", "K230002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
  {
    k_number: "K240002",
    device_name: "Alpha Glucose AI Pro",
    manufacturer: "MediTech Inc.",
    clearance_date: "2024-04-28",
    product_code: "NBW",
    predicate_k_numbers: ["K240001", "K210002", "K220002", "K230002"],
    device_class: "II",
    decision_code: "SESE",
    decision_description: "Substantially Equivalent",
  },
];

export default staticDevices;
